import { Inter } from "next/font/google";
import Navbar from "@components/layout/Navbar";
import CircularProgres from "@components/ui/CircularProgress";
import "./globals.css";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense fallback={<CircularProgres />}>
          <Navbar />
        </Suspense>
        {children}
      </body>
    </html>
  );
}
